/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FlatOwnerPublic {
  'id' : bigint,
  'username' : string,
  'ownerName' : string,
  'flatNo' : string,
  'blockNo' : string,
  'createdAt' : Time,
  'phone' : string,
  'maintenanceAmount' : bigint,
}
export interface SocietyOverview {
  'totalFlats' : bigint,
  'totalCollected' : bigint,
  'totalPendingDues' : bigint,
}
export type Time = bigint;
export interface Transaction {
  'id' : bigint,
  'entryDate' : Time,
  'transactionType' : TransactionType,
  'date' : string,
  'createdBy' : string,
  'flatOwnerId' : bigint,
  'description' : string,
  'amount' : bigint,
}
export type TransactionType = { 'Debit' : null } |
  { 'Credit' : null };
export interface UserProfile { 'name' : string, 'flatOwnerId' : [] | [bigint] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addManualTransaction' : ActorMethod<
    [bigint, TransactionType, string, bigint, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFlatOwner' : ActorMethod<
    [string, string, string, string, bigint, string, string],
    bigint
  >,
  'deleteFlatOwner' : ActorMethod<[bigint], undefined>,
  'deleteTransaction' : ActorMethod<[bigint], undefined>,
  'getAllFlatOwners' : ActorMethod<[], Array<FlatOwnerPublic>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFlatStatement' : ActorMethod<[bigint], Array<Transaction>>,
  'getMyBalance' : ActorMethod<[], bigint>,
  'getMyProfile' : ActorMethod<[], FlatOwnerPublic>,
  'getMyStatement' : ActorMethod<[], Array<Transaction>>,
  'getSocietyOverview' : ActorMethod<[], SocietyOverview>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkOwnerToPrincipal' : ActorMethod<[bigint, Principal], undefined>,
  'loginOwner' : ActorMethod<[string, string], [] | [FlatOwnerPublic]>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateFlatOwner' : ActorMethod<
    [bigint, string, string, string, string, bigint],
    undefined
  >,
  'updateMaintenanceDebit' : ActorMethod<[string], undefined>,
  'updateTransaction' : ActorMethod<
    [bigint, TransactionType, string, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];