/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TransactionType = IDL.Variant({
  'Debit' : IDL.Null,
  'Credit' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ExpenseVoucher = IDL.Record({
  'id' : IDL.Nat,
  'entryDate' : Time,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'payee' : IDL.Text,
  'voucherNo' : IDL.Text,
  'amount' : IDL.Nat,
  'remarks' : IDL.Text,
});
export const FlatOwnerPublic = IDL.Record({
  'id' : IDL.Nat,
  'username' : IDL.Text,
  'ownerName' : IDL.Text,
  'flatNo' : IDL.Text,
  'blockNo' : IDL.Text,
  'createdAt' : Time,
  'phone' : IDL.Text,
  'maintenanceAmount' : IDL.Nat,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'entryDate' : Time,
  'transactionType' : TransactionType,
  'date' : IDL.Text,
  'createdBy' : IDL.Text,
  'flatOwnerId' : IDL.Nat,
  'description' : IDL.Text,
  'amount' : IDL.Nat,
});
export const SocietyOverview = IDL.Record({
  'totalFlats' : IDL.Nat,
  'totalCollected' : IDL.Nat,
  'totalPendingDues' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExpenseVoucher' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addManualTransaction' : IDL.Func(
      [IDL.Nat, TransactionType, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFlatOwner' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteExpenseVoucher' : IDL.Func([IDL.Nat], [], []),
  'deleteFlatOwner' : IDL.Func([IDL.Nat], [], []),
  'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
  'getAllExpenseVouchers' : IDL.Func([], [IDL.Vec(ExpenseVoucher)], ['query']),
  'getAllFlatOwners' : IDL.Func([], [IDL.Vec(FlatOwnerPublic)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFlatStatement' : IDL.Func([IDL.Nat], [IDL.Vec(Transaction)], ['query']),
  'getOwnerBalance' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getOwnerStatement' : IDL.Func([IDL.Nat], [IDL.Vec(Transaction)], ['query']),
  'getSocietyOverview' : IDL.Func([], [SocietyOverview], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loginOwner' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(FlatOwnerPublic)],
      ['query'],
    ),
  'resetFinancialData' : IDL.Func([], [], []),
  'updateFlatOwner' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'updateMaintenanceDebit' : IDL.Func([IDL.Text], [], []),
  'updateTransaction' : IDL.Func(
      [IDL.Nat, TransactionType, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TransactionType = IDL.Variant({
    'Debit' : IDL.Null,
    'Credit' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExpenseVoucher = IDL.Record({
    'id' : IDL.Nat,
    'entryDate' : Time,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'payee' : IDL.Text,
    'voucherNo' : IDL.Text,
    'amount' : IDL.Nat,
    'remarks' : IDL.Text,
  });
  const FlatOwnerPublic = IDL.Record({
    'id' : IDL.Nat,
    'username' : IDL.Text,
    'ownerName' : IDL.Text,
    'flatNo' : IDL.Text,
    'blockNo' : IDL.Text,
    'createdAt' : Time,
    'phone' : IDL.Text,
    'maintenanceAmount' : IDL.Nat,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'entryDate' : Time,
    'transactionType' : TransactionType,
    'date' : IDL.Text,
    'createdBy' : IDL.Text,
    'flatOwnerId' : IDL.Nat,
    'description' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const SocietyOverview = IDL.Record({
    'totalFlats' : IDL.Nat,
    'totalCollected' : IDL.Nat,
    'totalPendingDues' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExpenseVoucher' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addManualTransaction' : IDL.Func(
        [IDL.Nat, TransactionType, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFlatOwner' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteExpenseVoucher' : IDL.Func([IDL.Nat], [], []),
    'deleteFlatOwner' : IDL.Func([IDL.Nat], [], []),
    'deleteTransaction' : IDL.Func([IDL.Nat], [], []),
    'getAllExpenseVouchers' : IDL.Func(
        [],
        [IDL.Vec(ExpenseVoucher)],
        ['query'],
      ),
    'getAllFlatOwners' : IDL.Func([], [IDL.Vec(FlatOwnerPublic)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFlatStatement' : IDL.Func([IDL.Nat], [IDL.Vec(Transaction)], ['query']),
    'getOwnerBalance' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getOwnerStatement' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getSocietyOverview' : IDL.Func([], [SocietyOverview], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loginOwner' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(FlatOwnerPublic)],
        ['query'],
      ),
    'resetFinancialData' : IDL.Func([], [], []),
    'updateFlatOwner' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'updateMaintenanceDebit' : IDL.Func([IDL.Text], [], []),
    'updateTransaction' : IDL.Func(
        [IDL.Nat, TransactionType, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };